"""empty message

Revision ID: 424283b1137d
Revises: 51f5ccfba190
Create Date: 2021-06-06 19:38:13.730261

"""

# revision identifiers, used by Alembic.
revision = '424283b1137d'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
