"""empty message

Revision ID: a08b00148947
Revises: 424283b1137d
Create Date: 2021-06-08 15:36:25.476285

"""

# revision identifiers, used by Alembic.
revision = 'a08b00148947'
down_revision = '424283b1137d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
